// src/lib/mock-data.js
export const MOCK_DATA = {
  productos: [
    {
      id: 'vape-3.5k',
      nombre: 'Vape 3500 Hits',
      imagen: '/imgs/vape-3.5k-card.png',
      descripcion:
        'Ideal para empezar, compacto y potente.',
    },
    {
      id: 'vape-20k',
      nombre: 'Vape 20,000 Hits',
      imagen: '/imgs/vape-20k-card.png',
      descripcion: 'Batería de larga duración, gran sabor.',
    },
    {
      id: 'vape-36k',
      nombre: 'Vape Pro 36,000 Hits',
      imagen: '/imgs/vape-36k-card.png',
      descripcion:
        'La experiencia definitiva, máximo vapor.',
    },
  ],
  inventario: [
    {
      producto_id: 'vape-3.5k',
      sabor: 'Mango',
      ciudad: 'Cochabamba',
      precio: '80',
      stock: '15',
      etiqueta: null,
    },
    {
      producto_id: 'vape-3.5k',
      sabor: 'Uva',
      ciudad: 'Santa Cruz',
      precio: '85',
      stock: '20',
      etiqueta: 'NUEVO',
    },
    {
      producto_id: 'vape-3.5k',
      sabor: 'Fresa',
      ciudad: 'Cochabamba',
      precio: '80',
      stock: '10',
      etiqueta: null,
    },
    {
      producto_id: 'vape-3.5k',
      sabor: 'Menta',
      ciudad: 'Santa Cruz',
      precio: '85',
      stock: '18',
      etiqueta: null,
    },
    {
      producto_id: 'vape-3.5k',
      sabor: 'Piña Colada',
      ciudad: 'Cochabamba',
      precio: '80',
      stock: '7',
      etiqueta: null,
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Blueberry Ice',
      ciudad: 'Cochabamba',
      precio: '150',
      stock: '12',
      etiqueta: 'TOP',
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Fresa Kiwi',
      ciudad: 'Cochabamba',
      precio: '150',
      stock: '8',
      etiqueta: null,
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Blueberry Ice',
      ciudad: 'Santa Cruz',
      precio: '155',
      stock: '0',
      etiqueta: null,
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Watermelon Ice',
      ciudad: 'Cochabamba',
      precio: '150',
      stock: '10',
      etiqueta: null,
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Peach Ice',
      ciudad: 'Santa Cruz',
      precio: '155',
      stock: '15',
      etiqueta: null,
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Grape Ice',
      ciudad: 'Cochabamba',
      precio: '150',
      stock: '9',
      etiqueta: null,
    },
    {
      producto_id: 'vape-20k',
      sabor: 'Fresa Kiwi',
      ciudad: 'Santa Cruz',
      precio: '155',
      stock: '11',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Triple Berry',
      ciudad: 'Cochabamba',
      precio: '220',
      stock: '5',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Miami Mint',
      ciudad: 'Cochabamba',
      precio: '220',
      stock: '10',
      etiqueta: 'NUEVO',
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Strawberry Banana',
      ciudad: 'Santa Cruz',
      precio: '225',
      stock: '8',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Blue Razz Ice',
      ciudad: 'Cochabamba',
      precio: '220',
      stock: '12',
      etiqueta: 'TOP',
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Watermelon Bubblegum',
      ciudad: 'Santa Cruz',
      precio: '225',
      stock: '7',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Cherry Bomb',
      ciudad: 'Cochabamba',
      precio: '220',
      stock: '4',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Cool Mint',
      ciudad: 'Santa Cruz',
      precio: '225',
      stock: '14',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Lush Ice',
      ciudad: 'Cochabamba',
      precio: '220',
      stock: '6',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Pineapple Coconut',
      ciudad: 'Santa Cruz',
      precio: '225',
      stock: '9',
      etiqueta: null,
    },
    {
      producto_id: 'vape-36k',
      sabor: 'Triple Berry',
      ciudad: 'Santa Cruz',
      precio: '225',
      stock: '3',
      etiqueta: null,
    },
  ],
  puntos: [
    {
      id: 'cbba-norte',
      ciudad: 'Cochabamba',
      nombre: 'Sucursal Norte',
      direccion: 'Av. América #123',
      lat: '-17.37',
      lng: '-66.15',
      horario: 'L-V 09:00-18:00',
    },
    {
      id: 'scz-centro',
      ciudad: 'Santa Cruz',
      nombre: 'Punto Central SCZ',
      direccion: 'Calle 21 de Mayo, Esq. Ayacucho',
      lat: '-17.78',
      lng: '-63.18',
      horario: 'L-S 10:00-19:00',
    },
    {
      id: 'cbba-sud',
      ciudad: 'Cochabamba',
      nombre: 'Sucursal Sud',
      direccion: 'Av. Petrolera Km 4.5',
      lat: '-17.425',
      lng: '-66.138',
      horario: 'L-V 09:00-18:00',
    },
    {
      id: 'cbba-prado',
      ciudad: 'Cochabamba',
      nombre: 'Punto El Prado',
      direccion: 'Paseo de El Prado #255',
      lat: '-17.393',
      lng: '-66.157',
      horario: 'L-S 10:00-20:00',
    },
    {
      id: 'cbba-sacaba',
      ciudad: 'Cochabamba',
      nombre: 'Sucursal Sacaba',
      direccion: 'Plaza 6 de Agosto, Sacaba',
      lat: '-17.403',
      lng: '-66.042',
      horario: 'L-V 09:00-17:00',
    },
    {
      id: 'cbba-quillacollo',
      ciudad: 'Cochabamba',
      nombre: 'Punto Quillacollo',
      direccion: 'Plaza Bolivar, Quillacollo',
      lat: '-17.395',
      lng: '-66.279',
      horario: 'L-S 09:00-18:00',
    },
    {
      id: 'scz-equipetrol',
      ciudad: 'Santa Cruz',
      nombre: 'Sucursal Equipetrol',
      direccion: 'Av. San Martín, Equipetrol Norte',
      lat: '-17.763',
      lng: '-63.194',
      horario: 'L-S 10:00-21:00',
    },
    {
      id: 'scz-ventura',
      ciudad: 'Santa Cruz',
      nombre: 'Punto Ventura Mall',
      direccion: 'Ventura Mall, 4to Anillo',
      lat: '-17.755',
      lng: '-63.198',
      horario: 'L-D 10:00-22:00',
    },
    {
      id: 'scz-plan3000',
      ciudad: 'Santa Cruz',
      nombre: 'Sucursal Plan 3000',
      direccion: 'Av. Paurito, Plan 3000',
      lat: '-17.841',
      lng: '-63.145',
      horario: 'L-S 09:00-19:00',
    },
  ],
  promos: [
    {
      codigo: 'BIENVENIDO',
      tipo: 'porcentaje',
      valor: '10',
      activo: 'Si',
    },
    {
      codigo: 'VAPPEO20',
      tipo: 'fijo',
      valor: '20',
      activo: 'Si',
    },
    {
      codigo: 'INACTIVO',
      tipo: 'porcentaje',
      valor: '50',
      activo: 'No',
    },
    {
      codigo: 'FINDEANO',
      tipo: 'fijo',
      valor: '30',
      activo: '2025-12-31',
    },
  ],
  marketing: [
    {
      id: 'hero_quote',
      valor:
        '🔥 ¡Lanzamiento de nuestra web usa el código "VAPEO" para un 10% de descuento! - Prueba el nuevo sabor Mango en vape de 20k - Ahora hacemos envíos al interior de país!',
    },
  ],
}
